s/AM/a\.m\./g
s/EST/Eastern\ Standard/g
s/Sun/Sunday,/g
s/Tue/Tuesday,/g
s/Thu/Thursday,/g
s/Mon/Monday,/g
s/Wed/Wednesday,/g
s/Fri/Friday,/g
s/Sat/Saturday,/g
s/[0-9]\{4,\}/&\./g
s/Jan/January/g
s/Feb/February/g
s/Mar/March/g
s/Apr/April/g
s/May/May/g
s/Jun/June/g
s/Jul/July/g
s/Aug/August/g
s/Sep/Spetember/g
s/Oct/October/g
s/Nov/November/g
s/Dec/December/g